# frozen_string_literal: true

module OmarchyUI
  ICON_NAMES = %i[
    ruby phone plus minus reset refresh house gear search xmark check menu user bell wifi bluetooth
    volume_high volume_low volume_off play pause stop trash edit folder file download upload link lock
    unlock eye eye_slash star heart info warning circle_info circle_check circle_xmark arrow_left
    arrow_right arrow_up arrow_down chevron_left chevron_right chevron_up chevron_down calendar clock
    camera image music terminal code copy save power globe location pin android apple
  ].freeze

  COMPONENTS = {
    container: [%i[spacing padding bordered visible], %i[click], true],
    row: [%i[spacing alignment visible], %i[click], true],
    column: [%i[spacing alignment visible], %i[click], true],
    grid: [%i[columns rows spacing row_spacing column_spacing visible], %i[click], true],
    row_layout: [%i[spacing alignment visible], %i[click], true],
    column_layout: [%i[spacing alignment visible], %i[click], true],
    grid_layout: [%i[columns rows spacing row_spacing column_spacing alignment visible], %i[click], true],
    flow: [%i[spacing orientation width height visible], %i[click], true],
    center: [%i[padding spacing visible], %i[click], true],
    card: [%i[padding spacing color radius border_color accent visible], %i[click], true],
    stack: [%i[visible], %i[click], true],
    scroll: [%i[width height clip visible], %i[click], true],
    rectangle: [%i[width height color radius border_color border_width padding visible], %i[click], true],
    border_overlay: [%i[color width_spec gradient_colors gradient_angle radius visible], [], false],
    aspect_ratio: [%i[ratio width height clip visible], %i[click], true],
    constrained_box: [%i[width height min_width min_height max_width max_height clip visible], %i[click], true],
    fitted_box: [%i[width height fit alignment clip visible], %i[click], true],
    wrap: [%i[width height spacing orientation layout_direction visible], %i[click], true],
    split_view: [%i[width height orientation visible], %i[click resize], true],
    stack_layout: [%i[current_index width height visible], %i[click change], true],
    layout_item_proxy: [%i[target width height fill_width fill_height preferred_width preferred_height minimum_width minimum_height maximum_width maximum_height alignment margins left_margin top_margin right_margin bottom_margin visible], %i[target_change], false],
    loader: [%i[active asynchronous width height visible], %i[click loaded status], true],
    flickable: [%i[width height content_width content_height direction bounds_behavior interactive clip visible], %i[click scroll flick_start flick_end], true],
    focus_scope: [%i[focus active_focus width height visible], %i[click focus blur], true],
    flipable: [%i[flipped axis duration easing interactive width height visible], %i[click change], true],
    border_image: [%i[source width height border_left border_top border_right border_bottom horizontal_tile vertical_tile asynchronous cache mirror smooth visible], %i[click loaded error status], true],
    window: [%i[title x y width height minimum_width minimum_height maximum_width maximum_height color visible visibility modality flags opacity content_orientation], %i[close visible_change active_change visibility_change move resize], true],
    application_window: [%i[title x y width height minimum_width minimum_height maximum_width maximum_height color background visible visibility modality flags opacity content_orientation layout_direction font_family font_size], %i[close visible_change active_change visibility_change move resize focus_change], true],
    text: [%i[text style size bold color wrap width visible], [], false],
    label: [%i[text color size bold width wrap elide horizontal_alignment vertical_alignment maximum_lines format visible], %i[link], false],
    rich_text: [%i[text color link_color size bold width wrap maximum_lines visible], %i[link], false],
    markdown: [%i[text color link_color size width wrap maximum_lines base_url visible], %i[link], false],
    selectable_text: [%i[text color selection_color selected_text_color size bold width wrap format visible], %i[selection link], false],
    icon: [%i[name text size color visible], [], false],
    tooltip: [%i[text delay timeout foreground background border font_family font_size visible], [], false],
    image: [%i[source width height fill_mode visible], [], false],
    vector_image: [%i[source width height fill_mode renderer trusted asynchronous_shapes animation_loops animation_paused visible], %i[source_change], false],
    font_loader: [%i[source visible], %i[loaded error status], false],
    text_metrics: [%i[text font_family font_size bold italic letter_spacing word_spacing elide elide_width visible], %i[metrics], false],
    animated_image: [%i[source width height fill_mode playing paused speed asynchronous cache mirror smooth visible], %i[frame loaded error status], false],
    video: [%i[source width height auto_play loops volume muted playback_rate fill_mode orientation mirrored visible], %i[play pause stop error position duration], false],
    audio: [%i[source auto_play playback loops volume muted playback_rate visible], %i[play pause stop error position duration], false],
    avatar: [%i[source name size radius background foreground font_size asynchronous cache visible], %i[click loaded error], false],
    badge: [%i[value maximum dot size minimum_width padding background foreground font_size visible], %i[click], false],
    chip: [%i[text icon selected deletable enabled background selected_background foreground selected_foreground accent height radius horizontal_padding spacing font_size icon_size visible], %i[click change delete], false],
    spacer: [%i[width height visible], [], false],
    button: [%i[text icon tooltip selected active cursor focusable bordered foreground background accent font_family font_size icon_size icon_rotation icon_spinning horizontal_padding vertical_padding left_align tooltip_background tooltip_foreground tooltip_border], %i[click right_click hover], false],
    round_button: [%i[text icon checked checkable enabled diameter foreground background checked_background accent font_family font_size icon_size visible], %i[click change press release hover], false],
    tool_button: [%i[text icon checked checkable enabled width height foreground background checked_background accent font_family font_size icon_size visible], %i[click change press release hover], false],
    delay_button: [%i[text delay enabled width height foreground background progress_background accent font_family font_size visible], %i[activate progress press release cancel], false],
    action_button: [%i[icon tooltip foreground hover_color font_family font_size size focusable cursor bordered], %i[click hover], false],
    bar_icon_button: [%i[icon tooltip active foreground active_color slot_size optical_size font_family font_size text_rotation keep_space dimmed concealed interactive], %i[click right_click middle_click wheel], false],
    bar_indicator: [%i[active active_icon inactive_icon active_tooltip inactive_tooltip indicator_block foreground active_color font_family font_size], %i[click right_click middle_click wheel], false],
    toggle: [%i[label description checked cursor rounded foreground accent font_family title_size description_size], %i[change hover], false],
    checkbox: [%i[label checked foreground accent background font_family font_size indicator_size spacing cursor], %i[change hover], false],
    radio_button: [%i[label value checked enabled foreground accent background font_family font_size indicator_size spacing visible], %i[click change hover], false],
    radio_group: [%i[value options orientation spacing enabled foreground accent background font_family font_size indicator_size item_spacing visible], %i[change hover], false],
    toggle_switch: [%i[checked busy interactive cursor cursor_ring cursor_pad rounded foreground accent track_height track_width knob_size knob_inset], %i[change hover], false],
    text_field: [%i[text placeholder password foreground accent selection_tint horizontal_padding vertical_padding cursor], %i[change submit focus blur input], false],
    text_area: [%i[text placeholder width height wrap read_only maximum_length foreground background accent selection_tint font_family font_size padding visible], %i[input change focus blur selection], false],
    search_field: [%i[text suggestions text_role live current_index width enabled foreground background accent font_family font_size visible], %i[input change search submit activate highlight clear focus blur], false],
    password_field: [%i[text placeholder revealable revealed width foreground accent selection_tint horizontal_padding vertical_padding visible], %i[input change submit focus blur reveal], false],
    number_field: [%i[label value from to step foreground accent font_family font_size field_width cursor], %i[change hover], false],
    slider: [%i[value minimum maximum step integer track_color fill_color knob_color track_height knob_size ticks tick_color], %i[input change right_click], false],
    range_slider: [%i[lower upper minimum maximum step orientation snap live width height foreground background accent visible], %i[input change], false],
    dial: [%i[value minimum maximum step start_angle end_angle snap wrap live input_mode size foreground background accent visible], %i[input change press release], false],
    spin_box: [%i[value minimum maximum step editable wrap prefix suffix width enabled foreground background accent font_family font_size visible], %i[change increase decrease], false],
    double_spin_box: [%i[value minimum maximum step decimals editable wrap prefix suffix width enabled foreground background accent font_family font_size visible], %i[change increase decrease], false],
    color_picker: [%i[color label title opened show_alpha no_buttons native_dialog width height enabled foreground background border_color radius font_family font_size visible], %i[input change accept reject open close], false],
    date_picker: [%i[date label placeholder format minimum maximum opened close_on_select width height popup_width enabled foreground muted background popup_background border_color accent radius font_family font_size visible], %i[input change open close navigate], false],
    time_picker: [%i[time label placeholder use_24_hour show_seconds minute_step second_step opened accept_text cancel_text width height popup_width enabled foreground muted background popup_background border_color accent radius font_family font_size visible], %i[input change accept reject open close], false],
    file_picker: [%i[path paths label placeholder title mode multiple filters current_folder default_suffix opened native_dialog accept_text cancel_text width height enabled foreground muted background border_color accent radius font_family font_size visible], %i[input change accept reject open close folder_change], false],
    folder_picker: [%i[path label placeholder title current_folder opened native_dialog accept_text cancel_text width height enabled foreground muted background border_color accent radius font_family font_size visible], %i[input change accept reject open close folder_change], false],
    font_picker: [%i[family label placeholder title point_size pixel_size weight italic underline strikeout opened native_dialog width height enabled foreground muted background border_color accent radius font_family font_size visible], %i[input change accept reject open close], false],
    dialog_button_box: [%i[buttons custom_buttons orientation alignment position centered spacing width height enabled foreground background accent font_family font_size visible], %i[click accept reject help], false],
    action: [%i[text icon icon_source icon_color icon_width icon_height enabled checkable checked shortcut visible], %i[trigger toggle change], false],
    action_group: [%i[action_ids exclusive enabled checked_action visible], %i[trigger change actions_change], false],
    page: [%i[title header_text footer_text show_header show_footer header_height footer_height layout spacing padding width height enabled background header_background footer_background foreground muted border_color radius font_family font_size title_size footer_size layout_direction visible], %i[click show hide focus blur title_change], true],
    pane: [%i[layout spacing padding left_padding right_padding top_padding bottom_padding width height enabled background foreground border_color border_width radius layout_direction clip visible], %i[click show hide focus blur], true],
    frame: [%i[layout spacing padding left_padding right_padding top_padding bottom_padding width height enabled background foreground border_color border_width radius layout_direction clip visible], %i[click show hide focus blur], true],
    group_box: [%i[title layout spacing padding left_padding right_padding top_padding bottom_padding width height enabled background foreground muted border_color border_width radius font_family font_size title_size title_alignment layout_direction clip visible], %i[click show hide focus blur title_change], true],
    tabs: [%i[labels current_index position tab_width tab_height width height enabled background content_background foreground muted accent border_color radius font_family font_size layout_direction visible], %i[input change tab_click show hide focus blur], true],
    tab_bar: [%i[items current_index position spacing tab_width width height enabled background foreground muted accent border_color radius font_family font_size layout_direction visible], %i[input change tab_click show hide focus blur], false],
    tab_button: [%i[text checked enabled icon icon_source icon_color icon_width icon_height shortcut auto_exclusive width height background checked_background foreground checked_foreground muted accent border_color border_width radius font_family font_size visible], %i[click change toggle press release hover focus blur], false],
    page_indicator: [%i[count current_index interactive spacing dot_size width height enabled background foreground accent radius visible], %i[input change show hide focus blur], false],
    stack_view: [%i[current_index animated width height enabled background border_color radius clip visible], %i[change push pop depth_change busy_change show hide focus blur], true],
    swipe_view: [%i[current_index orientation interactive width height enabled background border_color radius clip layout_direction visible], %i[input change count_change show hide focus blur], true],
    drawer: [%i[opened edge modal dim interactive drag_margin close_policy layout spacing padding width height enabled background foreground border_color radius visible], %i[open close about_to_show about_to_hide position_change show hide focus blur], true],
    navigation_rail: [%i[items current_index extended alignment spacing padding item_height width height enabled background foreground muted accent selected_background border_color radius font_family font_size icon_size visible], %i[input change select show hide focus blur], false],
    breadcrumb: [%i[items current_index separator spacing padding item_height width height enabled background foreground muted accent border_color radius font_family font_size icon_size visible], %i[input change select show hide focus blur], false],
    pagination: [%i[count page sibling_count show_first_last show_previous_next previous_text next_text first_text last_text spacing padding item_size width height enabled background foreground muted accent selected_background border_color radius font_family font_size visible], %i[input change select previous next first last show hide focus blur], false],
    expansion_panel: [%i[title subtitle expanded animated duration easing spacing padding header_height width height enabled background header_background expanded_background foreground muted accent border_color radius font_family font_size title_size subtitle_size indicator_size visible], %i[toggle change expand collapse show hide focus blur], true],
    accordion: [%i[titles subtitles expanded_indices multiple animated duration easing spacing padding header_height width height enabled background header_background expanded_background foreground muted accent border_color radius font_family font_size title_size subtitle_size indicator_size visible], %i[toggle change expand collapse show hide focus blur], true],
    tool_bar: [%i[position layout spacing padding width height enabled background foreground border_color radius layout_direction visible], %i[click position_change show hide focus blur], true],
    tool_separator: [%i[orientation thickness length padding color opacity enabled visible], %i[show hide], false],
    dropdown: [%i[label value options foreground background popup_border accent font_family row_height popup_row_height show_label cursor], %i[change hover], false],
    searchable_dropdown: [%i[label value options placeholder empty_text trigger_label foreground background popup_border accent font_family row_height popup_row_height popup_min_height show_label cursor], %i[change hover], false],
    multi_select: [%i[label values options options_command options_command_cwd placeholder empty_text no_selection_text trigger_label show_label foreground background popup_border accent font_family row_height popup_row_height popup_min_height cursor], %i[change hover], false],
    button_group: [%i[value options foreground background accent font_family font_size focusable cursor_index], %i[change hover], false],
    progress: [%i[value minimum maximum width height color visible], [], false],
    line_chart: [%i[values labels width height color fill_color grid_color line_width minimum maximum show_grid show_points point_size visible], %i[select hover], false],
    area_chart: [%i[values labels width height color fill_color grid_color line_width minimum maximum show_grid visible], %i[select hover], false],
    bar_chart: [%i[values labels width height colors grid_color minimum maximum show_grid bar_spacing visible], %i[select hover], false],
    separator: [%i[strength visible], [], false],
    divider: [%i[orientation length thickness indent end_indent color opacity visible], [], false],
    section_header: [%i[text visible], [], false],
    confirm_dialog: [%i[opened message cancel_text confirm_text selected_index background foreground scrim selected_background selected_text font_family corner_radius], %i[cancel confirm], false],
    panel_hero: [%i[title meta detail foreground font_family icon_size icon_opacity meta_opacity], [], false],
    optical_glyph: [%i[text size color debug_bounds visible], [], false],
    cursor_surface: [%i[cursor current outline bordered foreground accent fill current_fill], %i[click], true],
    widget_button: [%i[text font_family font_size foreground active_color active horizontal_margin vertical_padding fixed_width fixed_height text_rotation keep_space dimmed concealed interactive pressable use_active_color maintain_indicator_reveal label_visible has_visual_content tooltip], %i[click right_click middle_click wheel], false],
    list_view: [%i[items key_field label_field description_field icon_field selected orientation spacing width height empty_text visible], %i[activate change scroll], false],
    key_catcher: [%i[blocked visible], %i[move activate return close delete tab text], true]
  }.freeze

  DEFAULT_COMPONENTS = ComponentRegistry.new
  COMPONENTS.each do |name, (properties, events, container)|
    adapter = name.to_s.split("_").map(&:capitalize).join + ".qml"
    DEFAULT_COMPONENTS.register(name, qml: adapter, properties:, events:, container:)
  end
end
