# frozen_string_literal: true

require "json"

module OmarchyUI
  class ProjectConfig
    FILE_NAME = "config.rb"
    PROJECT_TYPES = %i[application plugin].freeze
    SLUG = /\A[a-z0-9]+(?:-[a-z0-9]+)*\z/
    SECTIONS = %i[left center right].freeze

    class Builder
      FIELDS = %i[type id name slug version author license description entrypoint].freeze

      FIELDS.each do |field|
        define_method(field) { |value| @values[field] = value }
      end

      def initialize
        @values = {}
      end

      def bar_widget(&definition)
        widget = WidgetBuilder.new
        widget.instance_eval(&definition)
        @values[:bar_widget] = widget.to_h
      end

      def build(path: FILE_NAME)
        ProjectConfig.new(@values, path:).tap(&:validate!)
      end
    end

    class WidgetBuilder
      FIELDS = %i[display_name description category default_section].freeze

      FIELDS.each do |field|
        define_method(field) { |value| @values[field] = value }
      end

      def initialize
        @values = {}
      end

      def to_h
        @values.dup
      end
    end

    attr_reader :path

    def self.define(&definition)
      raise ArgumentError, "project config requires a block" unless definition

      Builder.new.tap { |builder| builder.instance_eval(&definition) }.build
    end

    def self.generate(name:, slug:, kind:, author:, plugin_id: nil)
      type = kind.to_sym
      raise ArgumentError, "unsupported project type: #{type}" unless PROJECT_TYPES.include?(type)

      lines = [
        "# frozen_string_literal: true",
        "",
        "OmarchyUI.configure do",
        "  type #{type.inspect}"
      ]
      lines << "  id #{(plugin_id || "local.#{slug}").inspect}" if type == :plugin
      lines.concat([
        "  name #{name.inspect}",
        "  slug #{slug.inspect}",
        "  version \"0.1.0\""
      ])
      if type == :plugin
        lines.concat([
          "  author #{author.inspect}",
          "  license \"MIT\"",
          "  description #{"A Ruby-powered #{name} plugin generated by Omarchy UI.".inspect}",
          "  entrypoint \"main.rb\"",
          "",
          "  bar_widget do",
          "    display_name #{name.inspect}",
          "    description #{"Open #{name}.".inspect}",
          "    category \"System\"",
          "    default_section :right",
          "  end"
        ])
      else
        lines << "  entrypoint \"main.rb\""
      end
      lines << "end"
      lines.join("\n") + "\n"
    end

    def self.load(root)
      path = File.join(File.expand_path(root), FILE_NAME)
      return nil unless File.file?(path)

      value = Module.new.module_eval(File.read(path), path, 1)
      unless value.is_a?(ProjectConfig)
        raise ArgumentError, "#{FILE_NAME} must return an OmarchyUI::ProjectConfig"
      end

      new(value.to_h, path:).tap(&:validate!)
    rescue SyntaxError, NameError, NoMethodError => error
      raise ArgumentError, "invalid #{FILE_NAME}: #{error.message}"
    end

    def initialize(data, path:)
      @data = data
      @path = path
    end

    def type
      value = @data[:type]
      value.respond_to?(:to_sym) ? value.to_sym : value
    end

    def application? = type == :application
    def plugin? = type == :plugin
    def name = @data.fetch(:name)
    def slug = @data.fetch(:slug)
    def entrypoint = @data.fetch(:entrypoint)

    def to_h
      @data.dup
    end

    def manifest
      raise ArgumentError, "project config describes an application, not a plugin" unless plugin?

      widget = @data.fetch(:bar_widget)
      {
        "schemaVersion" => 1,
        "id" => @data.fetch(:id),
        "name" => name,
        "version" => @data.fetch(:version),
        "author" => @data.fetch(:author),
        "license" => @data.fetch(:license),
        "description" => @data.fetch(:description),
        "kinds" => ["service", "bar-widget", "panel"],
        "keepLoaded" => true,
        "entryPoints" => {
          "service" => "Service.qml",
          "barWidget" => "BarWidget.qml",
          "panel" => "Panel.qml"
        },
        "barWidget" => {
          "displayName" => widget.fetch(:display_name),
          "description" => widget.fetch(:description),
          "category" => widget.fetch(:category),
          "allowMultiple" => false,
          "defaultSection" => widget.fetch(:default_section).to_s
        }
      }
    end

    def write_manifest(destination)
      File.write(File.join(destination, "manifest.json"), JSON.pretty_generate(manifest) + "\n")
    end

    def validate!
      raise ArgumentError, "invalid project config" unless @data.is_a?(Hash)
      raise ArgumentError, "invalid project type" unless PROJECT_TYPES.include?(type)
      required_string!(:name)
      required_string!(:slug)
      raise ArgumentError, "invalid project slug" unless SLUG.match?(@data[:slug])
      required_string!(:version)
      required_string!(:entrypoint)
      validate_entrypoint!
      validate_plugin! if plugin?
      self
    end

    private

    def required_string!(key, object = @data)
      value = object[key]
      raise ArgumentError, "invalid project config field: #{key}" unless value.is_a?(String) && !value.strip.empty?

      value
    end

    def validate_entrypoint!
      parts = entrypoint.split(/[\\\/]/)
      if entrypoint.start_with?("/") || parts.empty? || parts.include?("..") || !entrypoint.end_with?(".rb")
        raise ArgumentError, "invalid project entrypoint"
      end
    end

    def validate_plugin!
      %i[id author license description].each { |key| required_string!(key) }
      raise ArgumentError, "invalid plugin id" unless VALID_ID.match?(@data[:id])
      raise ArgumentError, "plugin entrypoint must be main.rb" unless entrypoint == "main.rb"

      widget = @data[:bar_widget]
      raise ArgumentError, "plugin project config is missing bar widget metadata" unless widget.is_a?(Hash)

      %i[display_name description category].each { |key| required_string!(key, widget) }
      section = widget[:default_section]
      valid_section = section.respond_to?(:to_sym) && SECTIONS.include?(section.to_sym)
      raise ArgumentError, "invalid default bar section" unless valid_section
    end
  end

  def self.configure(&definition)
    ProjectConfig.define(&definition)
  end
end
